//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOL.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NOL.API.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access forbidden.
        /// </summary>
        public static string AccessForbidden {
            get {
                return ResourceManager.GetString("AccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement created successfully.
        /// </summary>
        public static string AdvertisementCreated {
            get {
                return ResourceManager.GetString("AdvertisementCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement deleted successfully.
        /// </summary>
        public static string AdvertisementDeleted {
            get {
                return ResourceManager.GetString("AdvertisementDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement not found.
        /// </summary>
        public static string AdvertisementNotFound {
            get {
                return ResourceManager.GetString("AdvertisementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement retrieved successfully.
        /// </summary>
        public static string AdvertisementRetrieved {
            get {
                return ResourceManager.GetString("AdvertisementRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvertisementsRetrieved.
        /// </summary>
        public static string AdvertisementsRetrieved {
            get {
                return ResourceManager.GetString("AdvertisementsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement status updated successfully.
        /// </summary>
        public static string AdvertisementStatusUpdated {
            get {
                return ResourceManager.GetString("AdvertisementStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement updated successfully.
        /// </summary>
        public static string AdvertisementUpdated {
            get {
                return ResourceManager.GetString("AdvertisementUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking canceled successfully.
        /// </summary>
        public static string BookingCanceled {
            get {
                return ResourceManager.GetString("BookingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking canceled successfully.
        /// </summary>
        public static string BookingCanceledSuccessfully {
            get {
                return ResourceManager.GetString("BookingCanceledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This booking cannot be canceled due to its current status.
        /// </summary>
        public static string BookingCannotBeCanceled {
            get {
                return ResourceManager.GetString("BookingCannotBeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking created successfully.
        /// </summary>
        public static string BookingCreated {
            get {
                return ResourceManager.GetString("BookingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking not found.
        /// </summary>
        public static string BookingNotFound {
            get {
                return ResourceManager.GetString("BookingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking points processed successfully.
        /// </summary>
        public static string BookingPointsProcessed {
            get {
                return ResourceManager.GetString("BookingPointsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking retrieved successfully.
        /// </summary>
        public static string BookingRetrieved {
            get {
                return ResourceManager.GetString("BookingRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings retrieved successfully.
        /// </summary>
        public static string BookingsRetrieved {
            get {
                return ResourceManager.GetString("BookingsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches retrieved successfully.
        /// </summary>
        public static string BranchesRetrieved {
            get {
                return ResourceManager.GetString("BranchesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch retrieved successfully.
        /// </summary>
        public static string BranchRetrieved {
            get {
                return ResourceManager.GetString("BranchRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel a booking that has already started.
        /// </summary>
        public static string CannotCancelStartedBooking {
            get {
                return ResourceManager.GetString("CannotCancelStartedBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set both car and category for advertisement.
        /// </summary>
        public static string CannotSetBothCarAndCategory {
            get {
                return ResourceManager.GetString("CannotSetBothCarAndCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car is not available.
        /// </summary>
        public static string CarNotAvailable {
            get {
                return ResourceManager.GetString("CarNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car not found.
        /// </summary>
        public static string CarNotFound {
            get {
                return ResourceManager.GetString("CarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car retrieved successfully.
        /// </summary>
        public static string CarRetrieved {
            get {
                return ResourceManager.GetString("CarRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars retrieved successfully.
        /// </summary>
        public static string CarsRetrieved {
            get {
                return ResourceManager.GetString("CarsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories retrieved successfully.
        /// </summary>
        public static string CategoriesRetrieved {
            get {
                return ResourceManager.GetString("CategoriesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category retrieved successfully.
        /// </summary>
        public static string CategoryRetrieved {
            get {
                return ResourceManager.GetString("CategoryRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click count incremented successfully.
        /// </summary>
        public static string ClickCountIncremented {
            get {
                return ResourceManager.GetString("ClickCountIncremented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery branch is not available.
        /// </summary>
        public static string DeliveryBranchNotAvailable {
            get {
                return ResourceManager.GetString("DeliveryBranchNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already confirmed.
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not verified. Please check your email for verification code.
        /// </summary>
        public static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email.
        /// </summary>
        public static string EmailSendingFailed {
            get {
                return ResourceManager.GetString("EmailSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification code sent successfully.
        /// </summary>
        public static string EmailVerificationSent {
            get {
                return ResourceManager.GetString("EmailVerificationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verified successfully.
        /// </summary>
        public static string EmailVerified {
            get {
                return ResourceManager.GetString("EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired points processed successfully.
        /// </summary>
        public static string ExpiredPointsProcessed {
            get {
                return ResourceManager.GetString("ExpiredPointsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra retrieved successfully.
        /// </summary>
        public static string ExtraRetrieved {
            get {
                return ResourceManager.GetString("ExtraRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras retrieved successfully.
        /// </summary>
        public static string ExtrasRetrieved {
            get {
                return ResourceManager.GetString("ExtrasRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvertisementsRetrieved.
        /// </summary>
        public static string FeaturedAdvertisementsRetrieved {
            get {
                return ResourceManager.GetString("FeaturedAdvertisementsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient loyalty points for this redemption.
        /// </summary>
        public static string InsufficientLoyaltyPoints {
            get {
                return ResourceManager.GetString("InsufficientLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date range.
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Or Password.
        /// </summary>
        public static string InvalidEmailORPassword {
            get {
                return ResourceManager.GetString("InvalidEmailORPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP code.
        /// </summary>
        public static string InvalidOtp {
            get {
                return ResourceManager.GetString("InvalidOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty points awarded successfully.
        /// </summary>
        public static string LoyaltyPointsAwarded {
            get {
                return ResourceManager.GetString("LoyaltyPointsAwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty points redeemed successfully.
        /// </summary>
        public static string LoyaltyPointsRedeemed {
            get {
                return ResourceManager.GetString("LoyaltyPointsRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty point summary retrieved successfully.
        /// </summary>
        public static string LoyaltyPointSummaryRetrieved {
            get {
                return ResourceManager.GetString("LoyaltyPointSummaryRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty point transactions retrieved successfully.
        /// </summary>
        public static string LoyaltyPointTransactionsRetrieved {
            get {
                return ResourceManager.GetString("LoyaltyPointTransactionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum redemption amount not met. You need at least 100 points to redeem..
        /// </summary>
        public static string MinimumRedemptionNotMet {
            get {
                return ResourceManager.GetString("MinimumRedemptionNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must set either car or category for advertisement.
        /// </summary>
        public static string MustSetEitherCarOrCategory {
            get {
                return ResourceManager.GetString("MustSetEitherCarOrCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP code has expired.
        /// </summary>
        public static string OtpExpired {
            get {
                return ResourceManager.GetString("OtpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change failed.
        /// </summary>
        public static string PasswordChangeFailed {
            get {
                return ResourceManager.GetString("PasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password are required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset email sent successfully.
        /// </summary>
        public static string PasswordResetEmailSent {
            get {
                return ResourceManager.GetString("PasswordResetEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed.
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successful.
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation password do not match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed.
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment processed successfully.
        /// </summary>
        public static string PaymentProcessed {
            get {
                return ResourceManager.GetString("PaymentProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving branch is not available.
        /// </summary>
        public static string ReceivingBranchNotAvailable {
            get {
                return ResourceManager.GetString("ReceivingBranchNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Please check your email for verification.
        /// </summary>
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View count incremented successfully.
        /// </summary>
        public static string ViewCountIncremented {
            get {
                return ResourceManager.GetString("ViewCountIncremented", resourceCulture);
            }
        }
    }
}
